apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: train
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: train
        tier: frontend
    spec:
      containers:
      - name: train-schedule
        image: docker.io/darkwunan/train-schedule:$(env.BUILD_ID)
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
© 2021 GitHub, Inc.
