apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: train
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: train
    tier: frontend
© 2021 GitHub, Inc.
